language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

r_github_packages:
  - hadley/testthat
  - hadley/dplyr
  - rstats-db/DBI
  - r-pkgs/callr
  
addons:
  apt_packages:
    - pandoc

after_failure:
  - ./travis-tool.sh dump_logs
