language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

r_github_packages:
  - hadley/testthat
  - hadley/dplyr
  - hadley/dbplyr
  - rstats-db/DBI
  
script:
  - |
    R CMD build .
    travis_wait 60 R CMD check MonetDBLite*tar.gz
  
addons:
  apt_packages:
    - pandoc

after_failure:
  - ./travis-tool.sh dump_logs
