clone_depth: 1
image:
- Visual Studio 2017
environment:
  matrix:
    - name: mingw64
      install_script: set "PATH=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;%PATH%"
      build_script: mingw32-make
      test_script: mingw32-make test

#    - mingw_bin: 'C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin'
#    - mingw_bin: 'C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin'
    - name: vs32
      install_script: cmake .
      build_script: cmake --build .
      test_script: Debug\readme.exe

install:
  - "%install_script%"
build_script:
  - "%build_script%"
test_script:
  - "%test_script%"
